version: '2'
services:
  app:
    container_name: app
    build:
      context: "./"
      dockerfile: ./deploy/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./testmusic:/var/testmusic
  web:
    container_name: web
    build:
      context: "./"
      dockerfile: ./deploy/web.dockerfile
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - 8090:80
  database:
    container_name: database
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=leafplayer"
      - "MYSQL_USER=leafplayer"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
volumes:
  dbdata:

