version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: deploy/web.dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "9090:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: deploy/app.dockerfile
        volumes:
            - ./:/var/www
            - ../testmusic:/var/www/testmusic
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
    database:
        image: mysql:5.6
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=leafplayer"
        ports:
           - "33061:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
         - PMA_ARBITRARY=1
        restart: always
        ports:
         - "9000:80"
        volumes:
         - /sessions
